### ISSUE TITLE
Mastodon Bridge

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#1]
ported from https://github.com/turt2live/waffle-matrix/issues/32

**Comment by turt2live** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mastodon](https://trello.com/c/2mRrHBEH/16-mastodon)

**Comment by homebeach** [comment]
Here is [Mastodon documentation repository](https://github.com/tootsuite/documentation). It contains also documentation of the API.

**Comment by homebeach** [comment]
There is [MXToot](https://github.com/ma1uta/mxtoot) and [mycete](https://github.com/qbit/mycete).

**Comment by shukon** [comment]
Both of them are discontinued.

**Comment by erebion** [comment]
@turt2live Please re-open, currently there seem to be only abandoned projects.

**Comment by turt2live** [comment]
There's still active bridges in the wild - https://docs.kazar.ma/ for example.
