### ISSUE TITLE
Create XMPP server that bridge Jabber messages to real matrix.org domain accounts

### ISSUE THREAD

**Issue by MurzNN** [turt2live/matrix-wishlist#103]
Will be good to launch an XMPP Jabber server on Matrix.org domain, that mirror all Matrix.org Matrix accounts, and bridge messages between XMPP & Matrix.

Maybe this feature can be done via some appservice like https://gitlab.com/uhoreg/matrix-appservice-prosody or some other way.

This will give ability for all XMPP users (and all other IM based on XMPP, ex Hangouts) to chat with users of Matrix.org Matrix server without creating Matrix account.

**Comment by homebeach** [comment]
https://github.com/matrix-org/matrix-bifrost
