### ISSUE TITLE
HipChat bridge

### ISSUE THREAD

**Issue by pcolmer** [turt2live/matrix-wishlist#106]
I'd like to see a HipChat/Matrix bridge, if anyone with more coding skills than me would like to take up the challenge :).

We use HipChat predominantly for its integration with other Atlassian products (e.g. notifications from JIRA) so I don't think we can move away from HipChat in preference to something else, but having everything under one roof (i.e. a single Matrix client) would be nice :).

**Comment by homebeach** [comment]
Here is [HipChat API](https://www.hipchat.com/docs/apiv2).

**Comment by homebeach** [comment]
HipChat supports XMPP so bridging would be probably possible with [Matrix Purple Bridge](https://github.com/matrix-org/matrix-appservice-purple).

**Comment by peterhoeg** [comment]
With hipchat having reached EOL, I assume this can be closed?
