### ISSUE TITLE
Steam bridge

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#11]
Ported from https://github.com/turt2live/waffle-matrix/issues/11

**Comment by turt2live** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Steam](https://trello.com/c/d3tX2zld/6-steam)

**Comment by homebeach** [comment]
Here are some plugins for Steam:

Miranda: https://wiki.miranda-ng.org/index.php?title=Plugin:Steam
Pidgin, Steam native: https://github.com/seishun/SteamPP
Pidgin, Steam mobile: https://github.com/EionRobb/pidgin-opensteamworks/tree/master/steam-mobile
Adium: https://www.adiumxtras.com/index.php?a=xtras&xtra_id=8339

**Comment by DoM1niC** [comment]
Could this help? https://github.com/ananace/matrix-puppet-steam

**Comment by homebeach** [comment]
Or this: https://github.com/icewind1991/mx-puppet-steam?

**Comment by turt2live** [comment]
Looks like this is done by a couple projects - closing.
