### ISSUE TITLE
Vkontakte (VK Messenger) to Matrix bot based and puppeted bridge

### ISSUE THREAD

**Issue by progserega** [turt2live/matrix-wishlist#114]
Bridge for exchenge messages between social network vk.com and matrix.

At network I found:
https://github.com/saber-nyan/vk2matrix-bot

But it is empty :-)

**Comment by turt2live** [comment]
It looks like the project you've linked does have code in it. What exactly are you looking to have bridged?

**Comment by commagray** [comment]
> https://github.com/saber-nyan/vk2matrix-bot

It's silly bot that reposts posts or articles from VK by requested link, but @saber-nyan had issues with thumbnails because of, quoting, «weak SDK» and dropped it. Meh.

**Comment by progserega** [comment]
It would be nice if we could send and receive messages of personal correspondence between VKontakte.ru and the matrix.

**Comment by homebeach** [comment]
Perhaps [here](https://vk.com/dev/manuals) would be some documentation that would help.

**Comment by MurzNN** [comment]
possible libraries to use:
- https://github.com/nikepan/govkbot
- https://github.com/Kutabe/vk
- https://github.com/urShadow/go-vk-api
- https://github.com/Vorkytaka/easyvk-go
- https://pypi.org/project/vk/

**Comment by MurzNN** [comment]
@progserega please update issue topic for better googling to something like:
`Vkontakte (VK Messenger) to Matrix bot based and puppeted bridge`

**Comment by progserega** [comment]
This is simple bot for only text messaging between matrix and VK:
https://github.com/progserega/MatrixVkBot

**Comment by turt2live** [comment]
Looks like https://github.com/progserega/MatrixVkBot is sufficiently advanced for this use case.

**Comment by dumprop** [comment]
But there no images from matrix to VK

**Comment by MurzNN** [comment]
Here https://github.com/innereq/mx-puppet-vk is much more improved version of VK <-> Matrix bridge, that works as application service, using Community bot and as Puppeted user.
