### ISSUE TITLE
Keybase bridge

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#117]
Unknown API

**Comment by homebeach** [comment]
Here is their [API documentation](https://keybase.io/docs/api/1.0).

**Comment by Berulacks** [comment]
> Here is their [API documentation](https://keybase.io/docs/api/1.0).

Their API only has to do with accessing encrpytion keys, nothing relating to chat.

**Comment by tulir** [comment]
https://github.com/keybase/keybase-bot

**Comment by homebeach** [comment]
There is this project: https://github.com/Half-Shot/matrix-keybase. So I guess this issue can be closed.
