### ISSUE TITLE
Matrix @mod 'Bot

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [turt2live/matrix-wishlist#121]
So, in the code, and maybe in the spec' is the ability for, AFAIK PL50 Mod's (probably hardcoded atm), to send messages containing `@room` to ping/highlight/mention **everyone**.  `↵↵¶`Also, IRC has sonething like, IIRC, `/wallchops <message>` to write to all room (channel) Moderators (Operators).  Matrix needs something like this for cases when abuses are occuring in a room and Mod' attention is needed.  But it is tedious to go through the userlist even on Riot-Web, and nearly impossible on i.e. Riot-Android, to pick out some Mod's, especially considering they are not ordered by, PL then AlphaNumeric.  `↵↵¶`Ideally any such 'bot should "[ACL Whisper](https://github.com/turt2live/matrix-wishlist/issues/78#issuecomment-386138955)" messages to Moderators, when such functionality comes to Matrix.  Or rather, such functionality for "`@mod`", even without but especially with "ACL Whisper", should be in the spec'.  `↵↵¶`However, in the interim a user might send a message i.e. `!mod <message>`, and the 'bot would responds with an immediately following message containing all Mod's Display Names, indicating the triggering room member's DN & MXID.  There is the possibility of abuse, so the 'bot needs to accept an `exclude` comnand, i.e. `!mod exclude <MXID>`.  `↵↵¶`At the end of the day, that would be a "good enough" interim solution to ensure room members help keep moderation proactive.

**Comment by Mikaela** [comment]
> Also, IRC has sonething like, IIRC, /wallchops <message> to write to all room (channel) Moderators (Operators). 

I think that would be `/msg @#channel message to ops`, but it would require being at least voiced (or did that only permit you to message voiced users, I am not entirely sure) and matrix-appservice-irc didn't handle it wheb I last checked.

**Comment by MilkManzJourDaddy** [comment]
What is done on IRC is just used as an example of the useful feature and nothing more.  Nothing even like `m.notice` even comes into play with this **simple interim solution**.  `@room` type functionality is only referenced for **future** forethought for spec' inclusion ala `spec-omission` [m.room.power_levels//notifications is undocumented matrix-org/matrix-spec-proposals#1101](https://github.com/matrix-org/matrix-doc/issues/1101) or https://docs.google.com/document/d/1qRdlg94cr9YXxPCwhW4HgI2oDrqQOUKX5HptZFBGf6o/mobilebasic •.  `↵↵¶`There are **absolutely no deleterious effects to IRC** and the interim solution could even work in a [Portal Room](https://github.com/MilkManzJourDaddy/matrix-org/wiki/Glossary-of-Terms-in-Matrix#portal-room) as all it would do is respond to an old school "trigger" and respond by "pinging"/"highlighting"/"mentioning" Mod's, indicating which MXID triggered the event.  `↵↵¶`IRC is irrelevant, inconsequential, and superfluous to that functionality.

**Comment by MilkManzJourDaddy** [comment]
Perhaps use `@mod <message_to_all_room_Moderators>` so there is a smooth transition for End Users if such functionality gets rolled into Matrix, similar to `﹫room <Message>`.  At such a time, there might be a slight bit of redundant "pinging" of Mod's, but they, or an Admin' should be able to deactivate the 'bot, maybe by raising the PL to trigger it, or just kicking it from the room.  `↵↵¶`But it would have served it's purpose.  And **currently** no such functionality is known to be in the pipeline.

**Comment by Mikaela** [comment]
In case backwards compatibility with ingrained habits of IRC users wanted to be involved, I would suggest watching for `!ops` and in case of Telegram, I am aware of multiple bots reacting on `@admin` even if that voculbary may be confusing.

**Comment by MilkManzJourDaddy** [comment]
It is up to a Matrix room Admin' and their Mod's to add their IRC nick' to their `keywords`, or the Dev'Op's of the appservice bridge 'bot to ensure pings translate, same with other platform.  `↵↵¶`**IT IS BEYOND THE SCOPE OF THIS 'BOT**.  I suggest taking it up in the Matrix spec' repo', or New Vector "Product" repo'.  `↵↵¶`Until `@mod <Message_to_Mod's> might be included in the spec' **preferably WITH "ACL Whisper", all this 'bot need do is send a room message with the DN & MXID that triggered it, mentioning the Mod's' current DNs, and, in case of a delay, **a Permalink to the message where it was triggered**.

**Comment by MilkManzJourDaddy** [comment]
It is up to IRCOp's to include whatever `/WALLCHOPS` in their "IRCd", or IRC chan' Op's to provide a 'bot which does that.  This is for **Matrix**.

**Comment by MilkManzJourDaddy** [comment]
The "ACL Whisper" feature is being discussed on the Riot "Product" repo' in, [Consider adding support for whispering in group rooms matrix-org/matrix-spec-proposals#3345](https://github.com/vector-im/riot-web/issues/3345), which defies logic if it is a Spec' thing.  However there is also an open Spec' issue of disputed relevance, depending how you apply and parse out: [We need a way to hide given messages from specific room members (SPEC-84) matrix-org/matrix-spec#56](https://github.com/matrix-org/matrix-doc/issues/482).

**Comment by gi-yt** [comment]
i think i might be able to add this feature to [merseklo](https://codeberg.org/aryak/merseklo). i will update here after i add the feature.

**Comment by gi-yt** [comment]
The feature has been added. I think you can close this issue now @turt2live @MilkManzJourDaddy
