### ISSUE TITLE
Fork mubot or Mimic Some of it's Functions

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [turt2live/matrix-wishlist#125]
Since GDPR, mubot has been silent.  But it's "echo" function was one helpful feature for photos where link previews may be unavailable #97 , and it's cumbersome, time consuming, uses data, bandwidth and storage, to download and post, especially on mobile.  Homeservers might be enabled to do such, but for now a 'bot will work.

**Comment by turt2live** [comment]
This is an operational concern for the bot's operator.
