### ISSUE TITLE
Alot Bot

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#127]
When someone says "alot":

![image](https://user-images.githubusercontent.com/1190097/41305078-0dd3a6f0-6e2f-11e8-9c95-1a93060ba58c.png)

**Comment by turt2live** [comment]
This might also be more appropriate with stickers, and probably needs a rate limit.

**Comment by MilkManzJourDaddy** [comment]
ivar has a function to trigger when someone types "alot" instead of "a lot".

**Comment by tulir** [comment]
My [react maubot plugin](https://github.com/maubot/reactbot)'s version 2.0 supports arbitrary responses to regexes. The example config includes an alot response.

**Comment by turt2live** [comment]
I'd call that done then, thanks tulir!
