### ISSUE TITLE
Gateway servers to other networks

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#131]
Gateway servers would bridge networks on a server level. For example IRC-Matrix gateway server would be both IRC server and Matrix server. When you create Matrix room on this server, it would automatically form IRC channel with the same name and join all the matrix users to IRC as IRC users and IRC users to Matrix as Matrix users. Matrix clients could have support for gateway servers. When you create a room there could be "Connect to IRC" button. You could also choose which IRC network you want to connect the room, what is the name equivalent of the room in IRC and so on. This way there would no need for external IRC bridges and there would be "out-of-box" compatibility with IRC.

**Comment by turt2live** [comment]
I'm not too sure what is being requested here. The IRC bridge already does map entire rooms (including their members) on both sides of the bridge. 

A "Connect to IRC" button would be a good thing to have, although it is something the particular client would have to implement.

**Comment by homebeach** [comment]
I mean there would be IRC-Matrix servers as part of the Matrix network. This way you would not need to install and maintain bridge by yourself. You could just look for these gateway servers in the Matrix network and if found you can use them to connect to IRC.

**Comment by turt2live** [comment]
That's already a thing in matrix though: https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks

**Comment by homebeach** [comment]
What about other networks? XMPP etc? All the open networks could be bridged this way.

**Comment by turt2live** [comment]
That's up to the bridge author. Bridges in general should support being used by anyone on the federation, and are capable to do so. Some bridges are written in a way where this isn't possible, but that's a design decision of the bridge.

**Comment by homebeach** [comment]
One cool thing would be a puppeting service. You could connect your acoounts from different networks with your Matrix account and when you talk in bridged room the server uses your account from other network to send the message. If #165 would be implemented, you could use the whole network with your connected account from Matrix.

**Comment by turt2live** [comment]
I'm closing this because offering a gateway is a design concern for bridges, not something someone can start a project with.
