### ISSUE TITLE
Google Hangouts bridge

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#141]
A bridge between Matrix and [Google Hangouts](https://en.wikipedia.org/wiki/Google_Hangouts).

**Comment by tulir** [comment]
There's Cadair's [matrix-appservice-hangouts](https://github.com/Cadair/matrix-appservice-hangouts) and matrix-hacks' [matrix-puppet-hangouts](https://github.com/matrix-hacks/matrix-puppet-hangouts)

**Comment by turt2live** [comment]
Closing due to hangouts bridges being a thing (thanks @tulir for pointing them out!)
