### ISSUE TITLE
Bridge with support for different LAN Messengers

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#160]
A bridge that bridges different [LAN Messenger](https://en.wikipedia.org/wiki/LAN_messenger) services into Matrix. One list of LAN Messengers can be found [here](https://en.wikipedia.org/wiki/Comparison_of_LAN_messengers).

**Comment by turt2live** [comment]
From what I can tell, each of the clients uses a different protocol. A generic bridge would be nice, although the protocols themselves should be split out into their own issues.

**Comment by homebeach** [comment]
According to [Pidgin web page](http://pidgin.im/about/) it support Bonjour so perhaps support for this is included into libpurple.
