### ISSUE TITLE
Integration into Bulletin Board System software

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#166]
Well nowdays people use Internet instead of Bulletin Board systems. However there exists hobbyist communities that still use BBS:s. Perhaps some BBS software could be modified to include Matrix support. This way BBS users would be able to chat with Matrix users. Also thread topics could be bridged to Matrix-rooms.

Here is one list of the available BBS Software for different platforms:
[A list of BBS software](https://en.wikipedia.org/wiki/List_of_BBS_software).

**Comment by turt2live** [comment]
Unfortunately this is too vague to triage correctly. BBS applications all appear to use different protocols, making bridging hard. Closing because this isn't something someone can start a project with.
