### ISSUE TITLE
[Mobile IM] KakaoTalk bridge

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#174]
A bridge between Matrix and [KakaoTalk](https://www.kakaocorp.com/service/KakaoTalk). [KakaoTalk Wikipedia page](https://en.wikipedia.org/wiki/KakaoTalk). KakaoTalk is a popular mobile instant messenger in South Korea.

**Comment by homebeach** [comment]
Here is [KakaoTalk developers page](https://developers.kakao.com/features/kakao). It contains information about available API:s. Here is [documentation for developers](https://developers.kakao.com/docs).

**Comment by homebeach** [comment]
Here is a blog post from someone trying to reverse engineer KakaTalk: https://www.bpak.org/blog/2011/06/kakaotalk-preliminary-research-analysis/.

**Comment by pierreN** [comment]
This would be a killer feature for me, I'm willing to spend some time on it. AFAIK most links explaining the protocol are too old and we would need to reverse engineer it from scratch ? If anyone is interested too let's talk about it in @me:pnn.sh !

**Comment by homebeach** [comment]
Here is a room for ideas about the bridge: https://matrix.to/#/#kakaotalk-bridge-ideas:miscworks.net.

**Comment by homebeach** [comment]
Here is an implementation for the bridge: https://src.miscworks.net/fair/matrix-appservice-kakaotalk/.
