### ISSUE TITLE
[Mobile IM] Threema bridge

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#177]
A bridge between Matrix and [Threema](https://threema.ch/en). [Threema Wikipedia page](https://en.wikipedia.org/wiki/Threema). Threema is a secure mobile instant messenger alternative to WhatsApp.

**Comment by homebeach** [comment]
Threema seems to have [Threema Message API](https://gateway.threema.ch/en/developer/api).

**Comment by MTRNord** [comment]
Remember that API costs money

**Comment by homebeach** [comment]
Reverse engineering project seems to [exist](https://github.com/blizzard4591/openMittsu).

**Comment by orrence** [comment]
There is also a C++ library for the protocol and a libpurple based plugin:
The library is here:
https://github.com/hbruintjes/ceema
And the plugin is in that repository, too:
https://github.com/hbruintjes/ceema/tree/master/src/threepl

**Comment by myxor** [comment]
Another possible approach would be using https://web.threema.ch/ similar to what the Whatsapp bridge does.

**Comment by Josue-T** [comment]
Yes, but comparing to whatsapp, If we install threema without google play something need to be done on the phone at each connection. With whatsapp it's only the first time.

**Comment by moepman** [comment]
Threema (Client) becoming open source mighty change the feasibility: https://threema.ch/en/blog/posts/open-source-and-new-partner

**Comment by g-voelker** [comment]
Threema is now open source. The code is hosted here: https://github.com/threema-ch

**Comment by mbiegert** [comment]
Just checking this out, seems like it should be relatively straight forward. I don't have experience with any matrix integration though. Maybe some adapting of one of the bridges from @tulir is possible?
I could help out on any project, but certainly won't have the time to stem this on my own in a reasonable time frame.

**Comment by sl5net** [comment]
> Threema is now open source. The code is hosted here: https://github.com/threema-ch

The Client is open source. Not the server

**Comment by systemofapwne** [comment]
I also really would like to see a threema bridge.

> > Threema is now open source. The code is hosted here: https://github.com/threema-ch
> 
> The Client is open source. Not the server

Yes, but I guess that this would already be fully sufficient in order to implement a bridge.

**Comment by MTRNord** [comment]
Just throwing https://threema-ch.github.io/app-remote-protocol/ into the mix which should do the job similar to the mautrix-whatsapp bridge

**Comment by MTRNord** [comment]
/me might want to do this as soon as rust has a proper appservice crate. I looked into the threema side and it seems to be pretty straightforward

**Comment by myxor** [comment]
It looks like Threema will release a Desktop client in the near future: https://twitter.com/ThreemaApp/status/1388160562731831305

**Comment by pReya** [comment]
Anyone interested in teaming up to tackle this? I'd love to do it, but I'm afraid I won't have enough time to do it alone.

**Comment by homebeach** [comment]
> Anyone interested in teaming up to tackle this? I'd love to do it, but I'm afraid I won't have enough time to do it alone.

How about establishing a room for this project and trying to find people from Matrix?

**Comment by balert** [comment]
I'd be interested too, maybe I could help a little.

**Comment by pReya** [comment]
I created a room for this endeavour. Feel free to join, so we can see how much interest and how much dev power we have for this topic. https://matrix.to/#/#threema-bridge:matrix.org

**Comment by pReya** [comment]
Quick initial assessment of the task ahead:

- The matrix side of things is pretty easy to handle. There's tons of SDKs and libraries which can help with interfacing to the Matrix network.
- The threema side is more critical. Even though, Threema is technically "open source", they don't publish any description of their protocol (only the crypto aspects).
- I've found two/three open source implementations of the threema protocol. Two of them haven't been touched in 3-4 years. Not sure if they're still working for all aspects. Probably should test this first.
	- [Ceema (C++)](https://github.com/hbruintjes/ceema)
	- [o3 (Go)](https://github.com/o3ma/o3)
	- [threema-rs] (https://github.com/bluec0re/threema-rs)

So, I guess there are two options now:
- Use existing library (mentioned above) to build a bridge (probably using either C++, Go or rust, depending on the lib)
- Implement threema protocol ourselves (pick any language you like)

Questions that I still have:
- How does [Threema Gateway](https://gateway.threema.ch) relate to the open source libraries/their official clients? Are the Android/iOS clients using the Threema Gateway API? Or is there a different API for their own, native clients and the paid Gateway product?

**Comment by freaktechnik** [comment]
When I quickly looked at threema earlier this year there seemed to be a couple of fairly maintained rust crates that implemented various aspects of the protocol.

**Comment by pReya** [comment]
@freaktechnik Seems there is a rust implementation based on o3 (see https://github.com/bluec0re/threema-rs). Thought it was just a C++ wrapper, but from what I can tell it's a complete rust implementation.

All the other crates I found are "Threema Gateway" related, which is their paid API product – and probably not what we want to use for a potential bridge.

**Comment by pReya** [comment]
I just applied for a grant to develop a Threema-Matrix-Bridge at the German Prototype fund (https://prototypefund.de/). I will know by the end of november, whether this works out. It would make it a lot easier to work on this, b/c then it would be paid work.

**Comment by myxor** [comment]
FYI: The desktop client for Threema is now available: 
https://threema.ch/en/blog/posts/threema-for-desktop

Only in .deb and .rpm package format until now and also no multi-device support is available but they are working on it.

**Comment by iMarv** [comment]
https://github.com/threema-ch/threema-web-electron
It is the web client wrapped into electron, so sadly nothing really new

**Comment by myxor** [comment]
You are right for the current state but we can hope for an independent client

> Thanks to multi-device functionality, version 2.0 no longer requires an active connection to your mobile device. This is to say that you’ll be able to use the desktop app even if your smartphone happens to be turned off.

**Comment by pReya** [comment]
> You are right for the current state but we can hope for an independent client
> 
> > Thanks to multi-device functionality, version 2.0 no longer requires an active connection to your mobile device. This is to say that you’ll be able to use the desktop app even if your smartphone happens to be turned off.

Currently, I don't think multi-device functionality will play any role in a potential bridge. This might be an idea for the future. But I think it would be best to start with a separate "bridge user", which uses its own license key. Similat to how most Matrix->Telegram bridging works.

**Comment by JonesGreen** [comment]
There is also https://github.com/blizzard4591/openMittsu

**Comment by pReya** [comment]
Our application the German Open Source funding program (https://prototypefund.de/) for a Matrix/Threema Bridge was accepted. However, money will not start flowing before March 2022. We hope we can get starte a little bit earlier than this (hopefully some time in Februray). By that time, we will create a separate GitHub project for it, so people can keep track, follow the progress and maybe help out.

**Comment by pReya** [comment]
We now have an ["official" repository for our bridge project, which will be called Threematrix](https://github.com/bitbatter/Threematrix). Feel free to star/follow our progress in the new repository. Actual code work will start on March 1st.

EDIT: We've just released our first alpha version, which can be tested by other users.

**Comment by homebeach** [comment]
As we now have a project for this, I guess this issue can be closed.
