### ISSUE TITLE
Twitch Bridge

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#2]
Ported from https://github.com/turt2live/waffle-matrix/issues/31

Use modular widgets to put the livestream in the room.

Base for twitch support: KittehOrg/KittehIRCClientLib@f1f3f0b

unsure about official docs

**Comment by turt2live** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Twitch](https://trello.com/c/5e9V9xpa/15-twitch)

**Comment by turt2live** [comment]
Related: https://github.com/matrix-org/go-neb/issues/194

**Comment by MTRNord** [comment]
Got a wip room for a puppet bridge https://matrix.to/#/#twitch-puppet-bridge:matrix.ffslfl.net  currently blocked a bit as I need to write a as go lib first

**Comment by MTRNord** [comment]
Also Dimension supports twitch widgets now

**Comment by MTRNord** [comment]
Github URL to my still WIP twitch puppet bridge: https://github.com/Nordgedanken/matrix-twitch-bridge

**Comment by turt2live** [comment]
Going to close this as @MTRNord's bridge looks to be progressing quite well.

**Comment by benparsons** [comment]
hey @MTRNord, what ever happened to https://github.com/Nordgedanken/matrix-twitch-bridge ?

**Comment by MTRNord** [comment]
> hey @MTRNord, what ever happened to https://github.com/Nordgedanken/matrix-twitch-bridge ?

I basically moved on from golang and also that bridge was a little Hard to maintain because of the IRC weirdness twitch has. It might be interesting to try running an irc bridge to twitch though 🤔

**Comment by klaernie** [comment]
Just out of curiosity I today setup a twitch chat bridge using [Matrix IRC Bridge](https://github.com/matrix-org/matrix-appservice-irc).

It has a few gotchas:
- you need a dedicated bot account on twitch
- authentication works using tokens, so both for the bot and every user you need to [create an access token on twitch](https://dev.twitch.tv/docs/irc/authenticate-bot), using something like https://twitchtokengenerator.com/ works fine. Pay close attention that you always prefix the access token with `oauth:` when putting it into the bridge config or when using `!storepass`.
- the IRC bridge must be configured with `nickTemplate: "$DISPLAY"` (not with the default `[m]` appended)
- else it's just an IRC bridge connecting to `irc.chat.twitch.tv`

For long-term usage I cannot tell yet, but I'd assume the access token expires after a while, when that happens one needs to either use the refresh token or run through the entire oauth flow again.

So there are a few things that one could automate better with a dedicated bridge - especially if one can build an automatic way for the oauth flow.
