### ISSUE TITLE
[Mobile IM] Apple Messages bridge

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#222]
A bridge between Matrix and [Apple Messages](https://support.apple.com/explore/messages). Here is [a developer page](https://developer.apple.com/documentation/messages).

**Comment by homebeach** [comment]
There seems to be [a project for this](https://github.com/matrix-hacks/matrix-puppet-imessage).

**Comment by non-Jedi** [comment]
Can we close issues for which a project already exists, please?

**Comment by DC7IA** [comment]
This seems to be about Apple Messages, not iMessages.

Supporting Apple Messages would also allow using SMS.

https://en.wikipedia.org/wiki/Messages_(Apple)
