### ISSUE TITLE
Instagram Direct bridge to Matrix

### ISSUE THREAD

**Issue by MurzNN** [turt2live/matrix-wishlist#254]
Will be good to have bridge Instagram Direct messages to Matrix. At now there are already many web services, that allow to send/receive Instagram Direct messages on desktop, so this is possible. Here https://www.npmjs.com/package/instagram-private-api is Node JS library that have support for Direct messages.

**Comment by MurzNN** [comment]
Here https://github.com/ifedapoolarewaju/igdm is opensource chat client in JS with Instagram Direct interface.

**Comment by Sorunome** [comment]
https://github.com/Sorunome/mx-puppet-instagram
