### ISSUE TITLE
Gitlab bot

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#29]
ref: https://github.com/matrix-org/go-neb/issues/127

**Comment by turt2live** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gitlab bot](https://trello.com/c/7WiDzswG/36-gitlab-bot)

**Comment by almereyda** [comment]
Could the https://github.com/turt2live/matrix-appservice-webhooks also be adapted for this?

**Comment by turt2live** [comment]
In a way, yes. A more purpose-built bot is going to be more capable though.

**Comment by tulir** [comment]
https://github.com/maubot/gitlab (has existed for a long time now, but I just noticed this issue is still open)

**Comment by turt2live** [comment]
Oops! I somehow missed this too. Closing - thanks @tulir :D
