### ISSUE TITLE
[Mobile IM] Peach bridge

### ISSUE THREAD

**Issue by homebeach** [turt2live/matrix-wishlist#306]
A bridge between Matrix and [Peach](http://peach.cool/). Here is  [the API documentation](https://peach.api-docs.io/1.0/welcome/introduction).

**Comment by homebeach** [comment]
Peach made it to [XKCD](https://pbs.twimg.com/media/C61eEt5WcAArPk3.jpg:large).

**Comment by lukateras** [comment]
Peach doesn't exist anymore, this issue can be closed 🍑🪦
