### ISSUE TITLE
Room IDs Do Not Render as Clickable in Riot-Web, Latest.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [turt2live/matrix-wishlist#351]
Room IDs, not Aliases, do not render as clickable in Riot-Web.  They do render as clickable in Riot-Android, latest on F-Droid.  

Kindly refer to this issue in the currenlty accepted New Vector "product" side repo'.

**Comment by turt2live** [comment]
This is not the repository for this concern.

**Comment by MilkManzJourDaddy** [comment]
So as a NV employee you should move the issue to where it will be accepted, rather than patently close it without referring it to an issue/repo' where it will not be also summarily closed without comprehension.

**Comment by turt2live** [comment]
This isn't a new vector repository so that hat I wear has no relevance here.
