### ISSUE TITLE
Room IDs Do Not Work with the Matrix.to Schema in Clients, nor the Site.  

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [turt2live/matrix-wishlist#352]
It seems Room IDs, not Aliases, do not work with matrix.to links, typically `/room/`.  And the matrix.to site does not recoginze Room IDs.  

Kindly refer to this issue in the currenlty accepted New Vector "product" side repo'.

**Comment by turt2live** [comment]
This is not the repository to track this concern.

**Comment by MilkManzJourDaddy** [comment]
So as a NV employee you should move the issue to where it will be accepted, rather than patently close it without referring it to an issue/repo' where it will not be also summarily closed without comprehension.

**Comment by turt2live** [comment]
See https://github.com/turt2live/matrix-wishlist/issues/351#issuecomment-541355843
