### ISSUE TITLE
3PID Mailto: Notification Target Cannot be Removed and Should NOT be Automatically Added.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [turt2live/matrix-wishlist#353]
This may be a legacy issue, but I removed my notification target mailto: (e-mail) address, maybe via the UI, and definitely via cURL, the latter answering back as successful.  However, in my MXID Settings the `notification target` remains, and I still see messaged in my filtering queue from `mailto:noreply@notifs.matrix.org` `subject: (subject contains non authorized characters)`.  

In a users' self-help room I Admin', someone complained about this feature spamming everone whom they enjoined to register on Matrix, automatically upon MXID creation, probably after a 3PID mailto: invite.  Their supported users were not technically inclined.  So even if the UI worked for removing the notification target, they complained it would be very difficult to walk their users through the process via telephone, et cetera.   This creates unnecessary angst, and this builds FUD on Matrix.  As an intermediate level tech' person, it does not make me happy to still see `mailto:noreply@notifs.matrix.org` hammerng away at my mitigation filters, despite using the UI and running the cURL indicated in the spec'.

Kindly refer to this issue in the currenlty accepted New Vector "product" side repo'.

**Comment by turt2live** [comment]
This is not an issue to track here.

**Comment by MilkManzJourDaddy** [comment]
So as a NV employee you should move the issue to where it will be accepted, rather than patently close it without referring it to an issue/repo' where it will not be also summarily closed without comprehension.

**Comment by turt2live** [comment]
See https://github.com/turt2live/matrix-wishlist/issues/351#issuecomment-541355843
