### ISSUE TITLE
[client feature] "I'll reply later"-button

### ISSUE THREAD

**Issue by ludwigbald** [turt2live/matrix-wishlist#363]
If I receive a message, but I don't have the time to craft a reply right now, I want to be able to:

1) Easily communicate that to the sender without feeling bad
2) Mark it as read, but also mark it as to-do on my side

This could be a quick action in the notifications or something in the client.

(1) could be achieved by sending a text message along the lines of "Thanks for the message, I'll reply later"
(2) could be achieved by storing the chat in account data. We also need a good UX solution for it.

**Comment by turt2live** [comment]
This would be best tracked either at the spec level or with whichever client the feature should be added to.
