### ISSUE TITLE
Joining rooms anonymously

### ISSUE THREAD

**Issue by gabrc52** [turt2live/matrix-wishlist#383]
Allow people to join rooms anonymously, so that they can send messages without revealing their identity. 

Even with no MSCs, it is theoretically possible to make a way of joining rooms anonymously. An application service could create a room per each person who wants to join the room anonymously, and puppet all the Matrix messages in the original room to the fake room. On the original room side, the bridge could act as one single "anonymous" user and forward all messages, reactions, typing indicators ("Anonymous is typing..."), etc.

This might be similar to #15 but for a different use case.

If there is one thing that I am questioning, is that if everyone decides to go anonymous, if it might be too much resource usage to create a room for every user in it. If 1000 people decide to join a room anonymously, it would be 1000 rooms.

**Comment by turt2live** [comment]
This is something that should be handled at the spec level, not with a bridge or third party software.
