### ISSUE TITLE
Nightly builds of riot-desktop

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#53]
May need to override the update settings to point to the nightly build server. Ideally this would be done by the riot team, but community versions would probably also work

**Comment by t3chguy** [comment]
Squirrel doesn't like downgrading so an option to twiddle to change whether you're stable or nightly won't be sane
but a secondary binary that can be installed alongside the stable one which updates nightly would work :)

**Comment by ordinarygulp** [comment]
I think this would be great! Lots of software has limits to keep from users jumping back and forth between beta and stable, so not unreasonable to assume we can keep 2 separate binaries.

**Comment by t3chguy** [comment]
We have these now :P

**Comment by JuniorJPDJ** [comment]
@turt2live should bee clooseed :D
