### ISSUE TITLE
WeChat bridge

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#71]
Source: XKCD edit (https://pbs.twimg.com/media/C61eEt5WcAArPk3.jpg:large)

Note: This may already be possible, please point me in the right direction if it is.

**Comment by homebeach** [comment]
Perhaps with [Bots framework](https://github.com/strongo/bots-framework)?

**Comment by CR0CKER** [comment]
This would actually be incredibly helpful to get people in China off Wechat more often. I don't know what Wechat's API allows for, but would be happy to help testing if someone's interested in getting started on this.

**Comment by cbwang2016** [comment]
This is definitely possible with https://github.com/littlecodersh/ItChat.
However only a few people in China have heard of Matrix right now. So this leads to a lack of developer to develop such project.

**However, I believe this could be a giant leap for making Matrix popular in Mainland China if this bridge can be developed successfully.**

**Comment by cbwang2016** [comment]
@turt2live Maybe this issue should be assigned with an **easy** Label? You can take a look at https://github.com/littlecodersh/ItChat (with Google Translate).

**Comment by turt2live** [comment]
Bridges are not weekend projects usually, even with a well-supported library. This is because the scope of a bridge can often be larger than just sending messages back and forth, and even getting that right is difficult.

**Comment by MurzNN** [comment]
For WeChat API here is Go libraries:
- https://gopkg.in/chanxuehong/wechat.v1
- https://gopkg.in/chanxuehong/wechat.v2

**Comment by ericmigi** [comment]
WeChaty is a pretty solid wechat API: https://github.com/Chatie/wechaty I know the creators and they've offered to troubleshoot/help out if anyone is interested in picking it up

**Comment by homebeach** [comment]
Here is [a Pidgin plugin](https://github.com/sbwtw/pidgin-wechat).

**Comment by huan** [comment]
Hi all, I'm the author of [Wechaty](https://github.com/Chatie/wechaty) that introduced by @ericmigi in the previous posts Wechaty is a Bot SDK for Wechat Individual Account which can help you create a bot in 6 lines of JavaScript/TypeScript, with Web / iPad / iOS protocol supported.

Recently I'm building a Wechat bridge for Matrix in TypeScript named [matrix-appservice-wechaty](https://github.com/huan/matrix-appservice-wechaty) after I meet @ericmigi in person at SV two months before.

With the great help from @ericmigi and @tulir, I hope I could be able to publish an alpha version this week. So please watch the project if you are interested, and stay tuned.

Any suggestion/feature/request/feedback will be welcome, please feel free to file an issue to share your ideas. And also, please create pull request if you want to make any progress faster! ;-)

**Comment by turt2live** [comment]
Awesome! Sounds like this issue can be closed now that there's an implementation out there.
