### ISSUE TITLE
WhatsApp Bridge

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-wishlist#74]
Source: XKCD edit (https://pbs.twimg.com/media/C61eEt5WcAArPk3.jpg:large)

Note: this may be particularly hard to implement due to restrictions on the WhatsApp side.

**Comment by DinizCabreira** [comment]
Yet it would be *so* awesome...

**Comment by rubo77** [comment]
Not sure, if we should put more effort into working together with FaceBook/WhatsApp, after reading the latest news about FB, where they sell the "secret" data of 50 Million Users.

Better put your work into the main stability and features of synapse in general.

**Comment by turt2live** [comment]
This is a wishlist, so anyone is free to work on whatever they want. Some people have different priorities of course, but that doesn't make an idea any less worthwhile.

**Comment by MTRNord** [comment]
This might help a lot https://github.com/sigalor/whatsapp-web-reveng  It uses the websocket that whatsapp web uses too. It might fix some banning issues

**Comment by homebeach** [comment]
What if you create new WhatsApp account for all the rooms you want to bridge?

**Comment by homebeach** [comment]
There exist attemps to bridge WhatsApp to other networks:

- [WhatsApp-Telegram bridge](https://github.com/rmed/wat-bridge)
- [WhatsApp-IRC Gateway](https://github.com/stenyak/breakbot)
- [WhatsApp-XMPP Gateway](https://github.com/stv0g/transwhat)
- [WhatsApp Gateway API](https://www.whatsmate.net/whatsapp-gateway-api.html)

Has somebody tried do these actually work?

**Comment by mvgorcum** [comment]
Note that whatsapp is quite serious about trying to prevent anyone from using whatsapp outside of the whatsapp app or webapp.

Even apps using the [android notification api got a cease and desist letter](https://www.xda-developers.com/whatsapp-sends-cease-desist-apps-native-android-api/).

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-whatsapp

**Comment by turt2live** [comment]
Closing as "in progress" for the project above :)

**Comment by mirh** [comment]
I believe it should be a bit more prominent that mautrix-whatsapp implements the web slave api, rather than the whole actual thing (like the other libraries based on yowsup, and as with what one would expect from basically all other protocols)

**Comment by tulir** [comment]
More prominent where/how? (also why are you commenting about it here?)

Usually one expects not to get banned right away, which is why the bridge uses the web app API instead of yowsup or something like that.

**Comment by mirh** [comment]
Sure, absolutely, it makes all sense of the world to do this when yowsup is totally out for the count. 
But if I search for "matrix whatsapp" on google, basically every official page I can find doesn't highlight the slightest this technically important caveat
(and that's why I thought to post here which is more general, rather than any repo specific)

It only becomes apparent if you check the linked dependencies description. 
And well, not saying it's a big deal at the end of the day, but for 2 minutes I had wrongly assumed you guys had reinvented the wheel, if I can explain.
