### ISSUE TITLE
Haiku bot

### ISSUE THREAD

**Issue by non-Jedi** [turt2live/matrix-wishlist#83]
## According to seequ_

splits a message to a haiku whenever it has exactly 17 syllables

## According to Magnap:

it must have 5+7+5 syllables, such that the splits fall on word boundaries

**Comment by turt2live** [comment]
When a message fits a haiku format, make it a haiku.

Eg:
> An old silent pond, A frog jumps into the pond, splash! Silence again.

turns into

> An old silent pond,
> A frog jumps into the pond,
> splash! Silence again.

**Comment by turt2live** [comment]
wip here: https://github.com/turt2live/matrix-haiku-bot/issues/4
