### ISSUE TITLE
Matrix room history purge bot (for delete old messages)

### ISSUE THREAD

**Issue by MurzNN** [turt2live/matrix-wishlist#85]
Will be good to implement bot that remove (redact) room messages older than specific time. This will partly solve issues like:
https://github.com/vector-im/riot-web/issues/2497
https://github.com/matrix-org/synapse/issues/2315
https://github.com/matrix-org/synapse/issues/1480
https://github.com/matrix-org/synapse/issues/1730

**Comment by turt2live** [comment]
I'm going to lump this into https://github.com/turt2live/matrix-wishlist/issues/81
