### ISSUE TITLE
new option for Rooms: "allow only users with password and email set"

### ISSUE THREAD

**Issue by rubo77** [turt2live/matrix-wishlist#94]
In many invite-only rooms it is essential, that users keep their account running, so an extra option besides "incite-only" would be needed to allow only users to access the room, if they have setup a password and email (maybe in two separate options)

(or is this repo not the right place for matrix wishes?)

**Comment by turt2live** [comment]
This particular request is probably best reported to riot-web. This repo is more for bot/bridge/tool wishes.
